spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/renaissance_bank_demo
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
openapi:
  dev-url=http://localhost:8080: